version: '3'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: nodedeploy
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
